version: '3.8'
services:
  sqlserver:
    build:
      context: .
    ports:
      - "1433:1433"
    volumes:
      - ./data:/var/opt/mssql
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Passw0rd"
    restart: always
